# Generated by Django 3.2.8 on 2021-10-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='HelpEmail', max_length=254, verbose_name='EMAIL'),
        ),
    ]
