# Generated by Django 3.2.8 on 2021-11-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FatherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='DaughterModel',
            fields=[
                ('fathermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.fathermodel')),
                ('daughter_name', models.CharField(max_length=80)),
            ],
            bases=('app1.fathermodel',),
        ),
        migrations.CreateModel(
            name='SonModel',
            fields=[
                ('fathermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.fathermodel')),
                ('son_name', models.CharField(max_length=80)),
            ],
            bases=('app1.fathermodel',),
        ),
    ]
