# Generated by Django 3.2.8 on 2021-11-09 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0004_alter_post_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.post')),
                ('likes', models.IntegerField()),
            ],
            bases=('app1.post',),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdBy',
            field=models.OneToOneField(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
