# Generated by Django 3.2.8 on 2021-11-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20211109_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='postId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='app1.post'),
            preserve_default=False,
        ),
    ]
