# Generated by Django 3.2.8 on 2021-11-09 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(related_name='singer', to=settings.AUTH_USER_MODEL),
        ),
    ]
