# Generated by Django 3.2.8 on 2021-11-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodel',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Market Name'),
        ),
    ]
