# Generated by Django 3.2.8 on 2021-11-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_marketmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxymarketmodel',
            options={'ordering': ['id']},
        ),
    ]
