# Generated by Django 4.0.1 on 2022-01-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(default='null', upload_to='', verbose_name='ff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='null', upload_to='', verbose_name='II'),
            preserve_default=False,
        ),
    ]
