# Generated by Django 3.2.8 on 2021-11-09 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(related_name='singer_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
