# Generated by Django 3.2.8 on 2021-11-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='postId',
            new_name='post',
        ),
    ]
