# Generated by Django 3.2.8 on 2021-11-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
