# Generated by Django 3.2.8 on 2021-11-03 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 11, 1, 6, 697965)),
        ),
    ]
